apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hugo
spec:
  replicas: 8
  template:
    metadata:
      labels:
        run: hugo
    spec:
      securityContext:
        fsGroup: 99
      containers:
        - name: hugo
          image: synax/project-asgard-deploy:1.0
          ports:
            - containerPort: 80
